# Generated by Django 4.2.3 on 2023-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('superiorID', models.IntegerField()),
                ('userType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leniency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('leniencyTasks', models.IntegerField(default=0)),
                ('leniencyExtraHour', models.IntegerField(default=0)),
                ('realExtraHour', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('max_Tasks', models.IntegerField()),
                ('max_ExtraHour', models.IntegerField()),
                ('hourly_rate', models.IntegerField()),
                ('date', models.CharField(max_length=6)),
            ],
        ),
    ]
