# Generated by Django 4.2.3 on 2023-09-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchy',
            name='userType',
        ),
        migrations.AddField(
            model_name='salary',
            name='userType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
