# Generated by Django 4.2.3 on 2024-08-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_hierarchy_usertype_salary_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('UpLineID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='canDefineTasks',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='structureID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
