# Generated by Django 4.2.3 on 2024-08-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_structure_hierarchy_candefinetasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='userID',
        ),
    ]
