# Generated by Django 4.2.3 on 2024-08-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_structure_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='structureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.structure'),
        ),
    ]
