# Generated by Django 4.2.3 on 2024-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_hierarchy_structureid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='structureID',
            field=models.IntegerField(),
        ),
    ]
