# Generated by Django 4.2.3 on 2024-08-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_hierarchy_structureid_hierarchy_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fee', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isValid', models.BooleanField()),
                ('employeesStructure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asEmployee', to='employee.structure')),
                ('employerStructure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asEmployer', to='employee.structure')),
            ],
        ),
    ]
