# Generated by Django 4.2.3 on 2024-08-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='UpLineID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DownLines', to='employee.structure'),
        ),
    ]
