# Generated by Django 4.2.3 on 2024-08-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_structure_uplineid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='UpLineID',
            new_name='upLine',
        ),
    ]
