# Generated by Django 4.2.3 on 2024-08-29 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0010_rename_uplineid_structure_upline'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='userID2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
