# Generated by Django 4.2.3 on 2023-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.IntegerField()),
                ('sender_name', models.CharField(max_length=30)),
                ('taskID', models.IntegerField()),
                ('send_date', models.DateTimeField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
