# Generated by Django 4.2.3 on 2023-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_systemmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='seen',
            new_name='seenByEmployee',
        ),
        migrations.AddField(
            model_name='chat',
            name='seenByInDirectSuperior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='seenBySuperior',
            field=models.BooleanField(default=False),
        ),
    ]
