# Generated by Django 4.2.3 on 2023-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_seen_chat_seenbyemployee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seenByValidator',
            field=models.BooleanField(default=False),
        ),
    ]
