# Generated by Django 4.2.3 on 2023-09-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_param_name_alter_param_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='param',
            old_name='name',
            new_name='key',
        ),
    ]
