# Generated by Django 4.2.3 on 2023-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('superior', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('validator', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('ValidatorFee', models.IntegerField()),
                ('delay_punishment', models.IntegerField()),
                ('final_payment', models.IntegerField(default=0)),
                ('ValidatorFinal_payment', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=6)),
                ('submit_date', models.DateField()),
                ('delivery_date', models.CharField(max_length=10)),
                ('end_request_accepted', models.BooleanField(blank=True, default=None, null=True)),
                ('end_request_date', models.DateField(blank=True, default=None, null=True)),
                ('inProgress', models.BooleanField(default=True)),
            ],
        ),
    ]
