# Generated by Django 4.2.3 on 2023-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_request_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
