# Generated by Django 4.2.3 on 2023-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_end_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
